{
 "title": "Crudapp dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count[1m])) ",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "RPS (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 50 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency 50 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency 99 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency max (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency 50 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, status) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 90 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \n      sum by (le, status) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 99 (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, status) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency max (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, status) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "HTTP status (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (rate(app_request_count[1m]))",
     "legendFormat": "{{ http_status }}"
    }
   ]
  },
  {
   "title": "500 count (crudapp)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (increase(app_request_count{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ http_status }}"
    }
   ]
  },
  {
   "title": "HTTP status (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "500 count (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Memory Usage (crudapp)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"crudapp-crud-chart.+\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage (crudapp)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"\", node=~\"minikube\", pod=~\"crudapp-crud-chart.+\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=\"crudapp\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "DB size (crudapp)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"crudapp\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  }
 ]
}