apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-config
---
apiVersion: v1
kind: Secret
metadata:
  name: crud-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "host=%s user=%s password=%s dbname=%s port=%s sslmode=disable" (include "postgresql.fullname" .) .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Values.postgresql.postgresqlDatabase .Values.postgresql.service.port | b64enc | quote }}

