apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "crud-chart.fullname" . }}
              port: 
                number: 9000
        - path: /otusapp/possokhov(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "crud-chart.fullname" . }}
              port: 
                number: 9000
