replicaCount: 3

image:
  repository: pingvincible/crud-service

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: cruduser
  postgresqlPassword: crudpass
  postgresqlDatabase: crudapp
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/app"]