replicaCount: 3

image:
  repository: pingvincible/crud-service
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true

postgresql:
  enabled: true
  postgresqlUsername: cruduser
  postgresqlPassword: crudpass
  postgresqlDatabase: crudapp
  service:
    port: "5432"